[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Which hasher is more secure to use, Blake2_128Concat or Twox64Concat?
"""
prompt.distractors = [
    "Twox64Concat",
    "Both are equally secure",
    "It depends on the specific use case",
]
answer.answer = "Blake2_128Concat"
id = "ec184e84-52ef-4b2c-a9cf-4a79cab76531"

[[questions]]
type = "MultipleChoice"
prompt.prompt = """
What is the main advantage of using the Twox64Concat hasher?
"""
prompt.distractors = [
    "It is more secure",
    "It is compatible with more data types",
    "It is easier to implement",
]
answer.answer = "It is more efficient"
id = "d0060eeb-396f-4896-ac6a-a9c140f112ee"
